// This file is generated by: flutterfire configure
// Run: dart pub global activate flutterfire_cli
//      flutterfire configure
// DO NOT edit manually.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web not configured.');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Platform not supported.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBaz1UnVPDhPcYxoVbvYB5VDu4hC-a3tI',
    appId: '1:766000170006:android:ae454be529682361bf2137',
    messagingSenderId: '766000170006',
    projectId: 'badminton-club-d3d01',
    storageBucket: 'badminton-club-d3d01.firebasestorage.app',
  );

  // Replace these values after running: flutterfire configure

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.badmintonClub',
  );
}